obc_img = {
    '0': 'https://i.imgur.com/hDI37FB.png',
    '1': 'https://i.imgur.com/UPLvY9X.png',
    '2': 'https://i.imgur.com/mJMa2L3.png',
    '3': 'https://i.imgur.com/H1zBoJ7.png',
    '4': 'https://i.imgur.com/67TIglP.png',
    '5': 'https://i.imgur.com/KmhskOq.png',
    '6': 'https://i.imgur.com/5unj2l8.png',
    '7': 'https://i.imgur.com/fbZnSUy.png'
}

calc_cell = {
    'al_east': 'Standings!A14:D18',
    'al_central': 'Standings!E14:H18',
    'al_west': 'Standings!I14:L18',
    'al_wildcard': 'Standings!S3:V14',
    'at_bat': 'Calculator!B6:F6',
    'awards': 'Calculator!A1:H1',
    'away_score': 'CalculatorBE!F3',
    'away_team': 'Starting Lineups!B2',
    'batter_name': 'Calculator!B6',
    'boxscore': 'Box Score!A1:A77',
    'calc_be': 'CalculatorBE!A3:CM3',
    'current_situation': 'Box Score!C6',
    'discord_name': 'Calculator!B22',
    'discord_ping': 'Calculator!B18:B21',
    'due_up': 'Box Score!C69',  # nice
    'event': 'Calculator!F6',
    'game_complete': 'Calculator!G12',
    'game_data': 'Starting Lineups!B2:H2',
    'game_end': 'Calculator!I5',
    'game_log': 'Game Log',
    'game_state': 'Calculator!B3:F3',
    'home_score': 'CalculatorBE!E3',
    'home_team': 'Starting Lineups!E2',
    'il_standings': 'Standings!F3:I16',
    'league': 'Starting Lineups!G2',
    'milr': 'Starting Lineups!G2',
    'milr_appointments': 'Player Appointments!J3:P30',
    'mlr_appointments': 'Player Appointments!A3:I32',
    'next_up': 'Box Score!C8',
    'nl_east': 'Standings!A4:D8',
    'nl_central': 'Standings!E4:H8',
    'nl_west': 'Standings!I4:L8',
    'nl_wildcard': 'Standings!N3:Q14',
    'pcl_standings': 'Standings!A3:D16',
    'pitch': 'Calculator!E6',
    'pitcher_name': 'Calculator!D6',
    'play_number': 'Calculator!G6',
    'reddit_ping': 'Calculator!B15',
    'result': 'Calculator!F8:F10',
    'lineup_check': 'Starting Lineups!B18:E18',
    'season_session': 'Template!C17',
    'swing': 'Calculator!C6',
    'ump_list': 'Calculator!F24:F26'
}

batting_types = {
    '1B': '1B/BB',
    'BC': 'Basic Contact',
    'BN': 'Basic Neutral',
    'BP': 'Basic Power',
    'EN': 'Extremely Neutral',
    'HK': 'Homerun/K',
    'MH': 'Max Homers',
    'P': 'Pitcher',
    'S': 'Speedy',
    'SF': 'Single Focused',
    'SM': 'Sacrifice Master',
    'TT': 'Three True Outcomes',
    'WC': 'Work the Count',
    'XB': 'Extra Base Focused'
}

pitching_types = {
    '1B': '1B/BB',
    'BB': 'Basic Balanced',
    'BF': 'Basic Finesse',
    'BS': 'Basic Strikeout',
    'EG': 'Extreme Groundball',
    'EN': 'Extreme Neutral',
    'FP': 'Flyball',
    'NH': 'No Homers',
    'NT': 'Nothing to Hit',
    'SF': 'Single Focused',
    'TD': 'Trust Your Defense',
    'TT': 'Three True Outcomes',
    'WC': 'Weak Contact'
}

hand_bonus = {
    'B': 'Balanced',
    'H': 'Anti-Homer',
    'S': 'Anti-Single'
}

milr_affiliate = {
    'ARI': 'BBB',
    'ATL': 'BAC',
    'BAL': 'TTT',
    'BOS': 'PUK',
    'CHC': 'HEL',
    'CIN': 'CWJ',
    'CLE': 'SAS',
    'COL': 'SAS',
    'CWS': 'SLT',
    'DET': 'BAC',
    'HOU': 'SGP',
    'KCR': 'SUP',
    'LAA': 'PBA',
    'LAD': 'POR',
    'MIA': 'CBC',
    'MIL': 'WWC',
    'MIN': 'FRG',
    'MTL': 'MVS',
    'NYM': 'CIM',
    'NYY': 'RBD',
    'OAK': 'PHB',
    'PHI': 'JEF',
    'PIT': 'AAL',
    'SDP': 'LID',
    'SEA': 'TAK',
    'SFG': 'MPD',
    'STL': 'MBT',
    'TBR': 'SAR',
    'TEX': 'SUP',
    'TOR': 'RBA'
}

stadium_image = {
    'ARI': 'https://i.imgur.com/ZzNi54t.png',
    'ATL': 'https://i.imgur.com/prvTr0u.png',
    'BAL': 'https://i.imgur.com/nKEZqzw.png',
    'BOS': 'https://i.imgur.com/kTFgR40.png',
    'CHC': 'https://i.imgur.com/yPQk4bc.png',
    'CIN': 'https://i.imgur.com/V3lU8rw.png',
    'CLE': 'https://i.imgur.com/k6hCgre.png',
    'COL': 'https://i.imgur.com/dRNnoo1.png',
    'CWS': 'https://i.imgur.com/q3F5D9l.png',
    'DET': 'https://i.imgur.com/qBGE3GV.png',
    'HOU': 'https://i.imgur.com/wWma73L.png',
    'KCR': 'https://i.imgur.com/Vq3EsTc.png',
    'LAA': 'https://i.imgur.com/pXzslBP.png',
    'LAD': 'https://i.imgur.com/h3y8OMU.png',
    'MIA': 'https://i.imgur.com/ozdMxFF.png',
    'MIL': 'https://i.imgur.com/7GiIIBP.png',
    'MIN': 'https://i.imgur.com/cBZ6hap.png',
    'MTL': 'https://i.imgur.com/0pHqrWB.png',
    'NYM': 'https://i.imgur.com/0dG69NA.png',
    'NYY': 'https://i.imgur.com/4zhZ8em.png',
    'OAK': 'https://i.imgur.com/jMskirU.png',
    'PHI': 'https://i.imgur.com/Ss28gcL.png',
    'PIT': 'https://i.imgur.com/BCY71yA.png',
    'SDP': 'https://i.imgur.com/BXGVWh3.png',
    'SEA': 'https://i.imgur.com/WujQvK9.png',
    'SFG': 'https://i.imgur.com/Uex5Rq9.png',
    'STL': 'https://i.imgur.com/H6QrapF.png',
    'TBR': 'https://i.imgur.com/q2sxEwi.png',
    'TEX': 'https://i.imgur.com/usXdKAY.png',
    'TOR': 'https://i.imgur.com/Nj3ncm5.png'
}
